server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuarios/**,/admin/**
        - id: registro-service
          uri: lb://registro-service
          predicates:
            - Path=/registros/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
