server:
  port: 8081

spring:
  application:
    name: usuario-service

  datasource:
    url: jdbc:postgresql://db.pftrnhcoinkmgbgerqse.supabase.co:5432/postgres
    username: postgres
    password: Vivi@19031996a
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
